export const cards = [
  {
    id: 0,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 2,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 3,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 4,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 5,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 6,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 7,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 8,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
  {
    id: 9,
    title: "AI Artists",
    desc: "Add talent to AI",
    image: "https://ychef.files.bbci.co.uk/1280x720/p0ff8hmx.jpg",
  },
];

export const projects = [
  {
    id: "1",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "2",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "3",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "4",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "5",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "6",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "7",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
  {
    id: "8",
    image: "/images/mobile.jpg",
    pp: "/images/mobile.jpg",
    cat: "gig1",
    username: "John cena",
  },
];
